version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: smartfarming-db
    restart: always
    environment:
      POSTGRES_DB: smartfarming
      POSTGRES_USER: smartfarmer
      POSTGRES_PASSWORD: smartproject
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: